services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: tcss460_group_project
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
    depends_on:
      - db
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:mysecretpassword@db:5432/tcss460_group_project

volumes:
  pgdata:
