services:
  db:
    image: postgres:17
    container_name: tcss460_db_project
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: tcss460_Project
    ports:
      - "5555:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
