openapi: 3.0.3
info:
  title: TCSS 460 Group Project API
  description: |
    **Team:** Group 7
    **Deployed URL:** https://tcss-460-group-7.onrender.com

    A RESTful API for the TCSS 460 group project.
  version: 0.1.0

servers:
  - url: http://localhost:3000
    description: Local development

tags:
  - name: General
    description: General-purpose routes

paths:

  /status:
    get:
      tags: [General]
      summary: Check status
      description: Checks the status of the server to ensure nothing was broken
      responses:
        '200':
          description: Checks the client status
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Status: OK'
